version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongo_presentation
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /Users/brandonbautista/Documents/Intekglobal/JavaScript/Presentations May 2023/Server/data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express_presentation
    restart: always
    ports: 
        - 8081:8081
    depends_on:
        - mongo
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: root
        ME_CONFIG_MONGODB_PORT: 27017  
    links:
        - mongo
    networks:
        - mongo-network

networks:
  mongo-network:
    driver: bridge